### ISSUE TITLE
pip installation fails when building trainingsample

### ISSUE THREAD

**Issue by janzd** [bghira/SimpleTuner#1759]
I tried installing the new version via pip but it fails.
Here's the error during installation.

```
  × Failed to build `trainingsample==0.2.4`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `maturin.build_wheel` failed (exit status: 1)

      [stdout]
      Running `maturin pep517 build-wheel -i /home/jovyan/.cache/uv/builds-v0/.tmpxsNIg7/bin/python --compatibility off`
      cargo 1.85.1 (d73d2caf9 2024-12-31)
      Rust not found, installing into a temporary directory

      [stderr]
      Python reports SOABI: cpython-312-x86_64-linux-gnu
      Computed rustc target triple: x86_64-unknown-linux-gnu
      Installation directory: /home/jovyan/.cache/puccinialin
      Rustup already downloaded
      Installing rust to /home/jovyan/.cache/puccinialin/rustup
      warn: It looks like you have an existing rustup settings file at:
      warn: /home/jovyan/.rustup/settings.toml
      warn: Rustup will install the default toolchain as specified in the settings file,
      warn: instead of the one inferred from the default host triple.
      info: profile set to 'minimal'
      info: default host triple is x86_64-unknown-linux-gnu
      warn: Updating existing toolchain, profile choice will be ignored
      info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
      info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
      Checking if cargo is installed
      📦 Including license file `LICENSE`
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.12 at /home/jovyan/.cache/uv/builds-v0/.tmpxsNIg7/bin/python
      📡 Using build options features from pyproject.toml
         Compiling clang-sys v1.8.1
         Compiling regex v1.11.3
         Compiling num-integer v0.1.46
         Compiling pyo3-build-config v0.22.6
         Compiling num-complex v0.4.6
         Compiling rand_core v0.6.4
         Compiling pxfm v0.1.24
         Compiling approx v0.5.1
         Compiling cc v1.2.39
         Compiling ab_glyph v0.2.32
         Compiling rayon-core v1.13.0
         Compiling equator v0.4.2
         Compiling thiserror v1.0.69
         Compiling profiling v1.0.17
         Compiling fax v0.2.6
      warning: clang-sys@1.8.1: could not execute `llvm-config` one or more times, if the LLVM_CONFIG_PATH environment variable is set to a full
      path to valid `llvm-config` executable it will be used to try to find an instance of `libclang` on your system: "couldn't execute `llvm-config
      --prefix` (path=llvm-config) (error: No such file or directory (os error 2))"
      error: failed to run custom build command for `clang-sys v1.8.1`

      Caused by:
        process didn't exit successfully:
      `/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/target/release/build/clang-sys-f7e7a38166174b78/build-script-build`
      (exit status: 101)
        --- stdout
        cargo:warning=could not execute `llvm-config` one or more times, if the LLVM_CONFIG_PATH environment variable is set to a full path to valid
      `llvm-config` executable it will be used to try to find an instance of `libclang` on your system: "couldn't execute `llvm-config --prefix`
      (path=llvm-config) (error: No such file or directory (os error 2))"

        --- stderr

        thread 'main' panicked at
      /home/jovyan/.cache/puccinialin/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clang-sys-1.8.1/build/dynamic.rs:225:45:
        called `Result::unwrap()` on an `Err` value: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so'], set the
      `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_BUILD_EXTENSION_MODULE="1"
      PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/home/jovyan/.cache/uv/builds-v0/.tmpxsNIg7/bin/python"
      PYTHON_SYS_EXECUTABLE="/home/jovyan/.cache/uv/builds-v0/.tmpxsNIg7/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module"
      "--features" "python-bindings" "--features" "opencv" "--features" "simd" "--message-format" "json-render-diagnostics" "--manifest-path"
      "/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/Cargo.toml" "--release" "--lib" "--crate-type" "cdylib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/jovyan/.cache/uv/builds-v0/.tmpxsNIg7/bin/python', '--compatibility', 'off']
      returned non-zero exit status 1

      hint: This usually indicates a problem with the package or the build environment.
  help: `trainingsample` (v0.2.4) was included because `simpletuner` (v2.2.1) depends on `trainingsample`
```

I tried doing it in a conda environment instead of uv just in case, but it failed too.

The Ubuntu version is 24.04.2.

**Comment by bghira** [comment]
you'll need to provide the full context, the trainingsample 0.2.4 has wheels available for ubuntu 24 and 22, not clear why it needs to be built from source. it's rather hard to build it from source because of the static OpenCV build chain.

**Comment by bghira** [comment]
```
root@n6bcdryoil:/notebooks# pip install trainingsample
Collecting trainingsample
  Downloading trainingsample-0.2.4-cp311-cp311-manylinux_2_35_x86_64.whl.metadata (705 bytes)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.11/dist-packages (from trainingsample) (1.26.3)
Requirement already satisfied: pillow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from trainingsample) (9.5.0)
Downloading trainingsample-0.2.4-cp311-cp311-manylinux_2_35_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 34.7 MB/s eta 0:00:00
Installing collected packages: trainingsample
Successfully installed trainingsample-0.2.4
```

here's what it looks like when installing the wheel inside ubuntu 22.

i am creating an ubuntu 24 system to test on, since i don't have any nvidia boxes handy.

**Comment by bghira** [comment]
i can reproduce the issue in ubuntu 24.04 LTS

**Comment by janzd** [comment]
I thought that my linux installation might be missing some packages based on the errors, so I tried to add some.

The error changed after I installed clang and libclang.

```
  × Failed to build `trainingsample==0.2.4`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `maturin.build_wheel` failed (exit status: 1)

      [stdout]
      Running `maturin pep517 build-wheel -i /home/jovyan/.cache/uv/builds-v0/.tmpnZTOMi/bin/python --compatibility off`
      cargo 1.85.1 (d73d2caf9 2024-12-31)
      Rust not found, installing into a temporary directory

      [stderr]
      Python reports SOABI: cpython-312-x86_64-linux-gnu
      Computed rustc target triple: x86_64-unknown-linux-gnu
      Installation directory: /home/jovyan/.cache/puccinialin
      Rustup already downloaded
      Installing rust to /home/jovyan/.cache/puccinialin/rustup
      warn: It looks like you have an existing rustup settings file at:
      warn: /home/jovyan/.rustup/settings.toml
      warn: Rustup will install the default toolchain as specified in the settings file,
      warn: instead of the one inferred from the default host triple.
      info: profile set to 'minimal'
      info: default host triple is x86_64-unknown-linux-gnu
      warn: Updating existing toolchain, profile choice will be ignored
      info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
      info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
      Checking if cargo is installed
      📦 Including license file `LICENSE`
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.12 at /home/jovyan/.cache/uv/builds-v0/.tmpnZTOMi/bin/python
      📡 Using build options features from pyproject.toml
         Compiling pyo3-build-config v0.22.6
         Compiling opencv v0.93.7
         Compiling imageproc v0.25.0
         Compiling pyo3-macros-backend v0.22.6
         Compiling pyo3-ffi v0.22.6
         Compiling pyo3 v0.22.6
      error: failed to run custom build command for `opencv v0.93.7`

      Caused by:
        process didn't exit successfully:
      `/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/target/release/build/opencv-98c09c3a3d456bf1/build-script-build`
      (exit status: 1)
        --- stdout
        cargo:rustc-check-cfg=cfg(ocvrs_opencv_branch_4)
        cargo:rustc-check-cfg=cfg(ocvrs_opencv_branch_34)
        cargo:rustc-check-cfg=cfg(ocvrs_opencv_branch_32)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_alphamat)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_aruco)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_aruco_detector)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_barcode)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_bgsegm)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_bioinspired)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_calib3d)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_ccalib)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_core)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudaarithm)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudabgsegm)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudacodec)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudafeatures2d)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudafilters)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudaimgproc)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudaobjdetect)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudaoptflow)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudastereo)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cudawarping)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_cvv)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_dnn)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_dnn_superres)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_dpm)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_face)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_features2d)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_flann)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_freetype)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_fuzzy)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_gapi)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_hdf)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_hfs)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_highgui)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_img_hash)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_imgcodecs)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_imgproc)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_intensity_transform)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_line_descriptor)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_mcc)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_ml)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_objdetect)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_optflow)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_ovis)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_phase_unwrapping)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_photo)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_plot)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_quality)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_rapid)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_rgbd)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_saliency)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_sfm)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_shape)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_signal)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_stereo)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_stitching)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_structured_light)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_superres)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_surface_matching)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_text)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_tracking)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_video)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_videoio)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_videostab)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_viz)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_wechat_qrcode)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_xfeatures2d)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_ximgproc)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_xobjdetect)
        cargo:rustc-check-cfg=cfg(ocvrs_has_module_xphoto)
        cargo:rerun-if-env-changed=OPENCV4_NO_PKG_CONFIG
        cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG
        cargo:rerun-if-env-changed=PKG_CONFIG
        cargo:rerun-if-env-changed=OPENCV4_STATIC
        cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
        cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
        cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
        cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
        cargo:rerun-if-env-changed=PKG_CONFIG_PATH
        cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
        cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
        cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
        cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
        cargo:rerun-if-env-changed=OPENCV_NO_PKG_CONFIG
        cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG
        cargo:rerun-if-env-changed=PKG_CONFIG
        cargo:rerun-if-env-changed=OPENCV_STATIC
        cargo:rerun-if-env-changed=OPENCV_DYNAMIC
        cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
        cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
        cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
        cargo:rerun-if-env-changed=PKG_CONFIG_PATH
        cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
        cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
        cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
        cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
        cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
        cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

        --- stderr
        === Crate version: 0.93.7
        === Environment configuration:
        ===   OPENCV_PACKAGE_NAME = None
        ===   OPENCV_PKGCONFIG_NAME = None
        ===   OPENCV_CMAKE_NAME = None
        ===   OPENCV_CMAKE_BIN = None
        ===   OPENCV_VCPKG_NAME = None
        ===   OPENCV_LINK_LIBS = None
        ===   OPENCV_LINK_PATHS = None
        ===   OPENCV_INCLUDE_PATHS = None
        ===   OPENCV_DISABLE_PROBES = None
        ===   OPENCV_MSVC_CRT = None
        ===   CMAKE_PREFIX_PATH = None
        ===   OpenCV_DIR = None
        ===   PKG_CONFIG_PATH = None
        ===   VCPKG_ROOT = None
        ===   VCPKGRS_DYNAMIC = None
        ===   VCPKGRS_TRIPLET = None
        ===   OCVRS_DOCS_GENERATE_DIR = None
        ===   DOCS_RS = None
        ===   PATH =
      Some("/home/jovyan/.cache/puccinialin/cargo/bin:/home/jovyan/.cache/uv/builds-v0/.tmpnZTOMi/bin:/home/jovyan/.local/bin:/home/jovyan/.local/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
        === Enabled features:
        ===   ALPHAMAT
        ===   ARUCO
        ===   ARUCO_DETECTOR
        ===   BARCODE
        ===   BGSEGM
        ===   BIOINSPIRED
        ===   CALIB3D
        ===   CCALIB
        ===   CUDAARITHM
        ===   CUDABGSEGM
        ===   CUDACODEC
        ===   CUDAFEATURES2D
        ===   CUDAFILTERS
        ===   CUDAIMGPROC
        ===   CUDAOBJDETECT
        ===   CUDAOPTFLOW
        ===   CUDASTEREO
        ===   CUDAWARPING
        ===   CVV
        ===   DEFAULT
        ===   DNN
        ===   DNN_SUPERRES
        ===   DPM
        ===   FACE
        ===   FEATURES2D
        ===   FLANN
        ===   FREETYPE
        ===   FUZZY
        ===   GAPI
        ===   HDF
        ===   HFS
        ===   HIGHGUI
        ===   IMGCODECS
        ===   IMGPROC
        ===   IMG_HASH
        ===   INTENSITY_TRANSFORM
        ===   LINE_DESCRIPTOR
        ===   MCC
        ===   ML
        ===   OBJDETECT
        ===   OPTFLOW
        ===   OVIS
        ===   PHASE_UNWRAPPING
        ===   PHOTO
        ===   PLOT
        ===   QUALITY
        ===   RAPID
        ===   RGBD
        ===   SALIENCY
        ===   SFM
        ===   SHAPE
        ===   SIGNAL
        ===   STEREO
        ===   STITCHING
        ===   STRUCTURED_LIGHT
        ===   SUPERRES
        ===   SURFACE_MATCHING
        ===   TEXT
        ===   TRACKING
        ===   VIDEO
        ===   VIDEOIO
        ===   VIDEOSTAB
        ===   VIZ
        ===   WECHAT_QRCODE
        ===   XFEATURES2D
        ===   XIMGPROC
        ===   XOBJDETECT
        ===   XPHOTO
        === Detected probe priority boost based on environment vars: pkg_config: false, cmake: false, vcpkg: false
        === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
        === Can't probe using: environment, continuing with other methods because: Some environment variables are missing
        === Probing OpenCV library using pkg_config
        === Can't probe using: pkg_config, continuing with other methods because:
        pkg-config exited with status code 1
        > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags opencv4

        The system library `opencv4` required by crate `opencv` was not found.
        The file `opencv4.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
        The PKG_CONFIG_PATH environment variable is not set.

        HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `opencv4.pc`.
        ,
        pkg-config exited with status code 1
        > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags opencv

        The system library `opencv` required by crate `opencv` was not found.
        The file `opencv.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
        The PKG_CONFIG_PATH environment variable is not set.

        HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `opencv.pc`.

        === Probing OpenCV library using cmake
        === cmake ninja probe command: cd
      "/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/target/release/build/opencv-fc91c3ef08d69754/out/cmake_probe_build"
      && "cmake" "-S" "/home/jovyan/.cache/puccinialin/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/opencv-0.93.7/cmake"
      "-DOCVRS_PACKAGE_NAME=OpenCV" "-DCMAKE_BUILD_TYPE=Release" "-G" "Ninja"
        === Probing with cmake ninja generator failed, will try Makefile generator, error: cmake returned an error
            stdout: "-- Configuring incomplete, errors occurred!\n"
            stderr: "CMake Error: CMake was unable to find a build program corresponding to \"Ninja\".  CMAKE_MAKE_PROGRAM is not set.  You probably
      need to select a different build tool.\nCMake Error: CMAKE_C_COMPILER not set, after EnableLanguage\nCMake Error: CMAKE_CXX_COMPILER not set,
      after EnableLanguage\n"
        === cmake makefiles probe command: cd
      "/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/target/release/build/opencv-fc91c3ef08d69754/out/cmake_probe_build"
      && "cmake" "-S" "/home/jovyan/.cache/puccinialin/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/opencv-0.93.7/cmake"
      "-DOCVRS_PACKAGE_NAME=OpenCV" "-DCMAKE_BUILD_TYPE=Release" "-G" "Unix Makefiles"
        === Probing with cmake Makefile generator failed, will try deprecated find_package, error: cmake returned an error
            stdout: "-- The C compiler identification is GNU 13.3.0\n-- The CXX compiler identification is GNU 13.3.0\n-- Detecting C compiler ABI
      info\n-- Detecting C compiler ABI info - done\n-- Check for working C compiler: /usr/bin/cc - skipped\n-- Detecting C compile features\n--
      Detecting C compile features - done\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Check for working CXX
      compiler: /usr/bin/c++ - skipped\n-- Detecting CXX compile features\n-- Detecting CXX compile features - done\n-- Configuring incomplete,
      errors occurred!\n"
            stderr: "CMake Error at CMakeLists.txt:5 (find_package):\n  By not providing \"FindOpenCV.cmake\" in CMAKE_MODULE_PATH this project
      has\n  asked CMake to find a package configuration file provided by \"OpenCV\", but\n  CMake did not find one.\n\n  Could not find a package
      configuration file provided by \"OpenCV\" with any\n  of the following names:\n\n    OpenCVConfig.cmake\n    opencv-config.cmake\n\n  Add
      the installation prefix of \"OpenCV\" to CMAKE_PREFIX_PATH or set\n  \"OpenCV_DIR\" to a directory containing one of the above files.  If
      \"OpenCV\"\n  provides a separate development package or SDK, be sure it has been\n  installed.\n\n\n"
        === cmake find-package compile probe command: cd
      "/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/target/release/build/opencv-fc91c3ef08d69754/out/cmake_probe_build"
      && "cmake" "-S" "/home/jovyan/.cache/puccinialin/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/opencv-0.93.7/cmake"
      "-DOCVRS_PACKAGE_NAME=OpenCV" "-DCMAKE_BUILD_TYPE=Release" "--find-package" "-DCOMPILER_ID=GNU" "-DLANGUAGE=CXX" "-DMODE=COMPILE"
      "-DNAME=OpenCV"
        === Can't probe using: cmake, continuing with other methods because: cmake returned an error
            stdout: "OpenCV not found.\n"
            stderr: "CMake Error: Run 'cmake --help' for all supported options.\n"
        === Probing OpenCV library using vcpkg_cmake
        === Can't probe using: vcpkg_cmake, continuing with other methods because: Could not find Vcpkg tree: No vcpkg installation found. Set the
      VCPKG_ROOT environment variable or run 'vcpkg integrate install'
        === Probing OpenCV library using vcpkg
        === Can't probe using: vcpkg, continuing with other methods because: Could not find Vcpkg tree: No vcpkg installation found. Set the
      VCPKG_ROOT environment variable or run 'vcpkg integrate install', Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT
      environment variable or run 'vcpkg integrate install'
        Error: "Failed to find installed OpenCV package using probes: environment, pkg_config, cmake, vcpkg_cmake, vcpkg, refer to
      https://github.com/twistedfall/opencv-rust#getting-opencv for help"
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_BUILD_EXTENSION_MODULE="1"
      PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/home/jovyan/.cache/uv/builds-v0/.tmpnZTOMi/bin/python"
      PYTHON_SYS_EXECUTABLE="/home/jovyan/.cache/uv/builds-v0/.tmpnZTOMi/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module"
      "--features" "python-bindings" "--features" "opencv" "--features" "simd" "--message-format" "json-render-diagnostics" "--manifest-path"
      "/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/Cargo.toml" "--release" "--lib" "--crate-type" "cdylib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/jovyan/.cache/uv/builds-v0/.tmpnZTOMi/bin/python', '--compatibility', 'off']
      returned non-zero exit status 1

      hint: This usually indicates a problem with the package or the build environment.
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and syncing.
```

After adding libopencv-dev:

```
  × Failed to build `trainingsample==0.2.4`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `maturin.build_wheel` failed (exit status: 1)

      [stdout]
      Running `maturin pep517 build-wheel -i /home/jovyan/.cache/uv/builds-v0/.tmpJ5vZA0/bin/python --compatibility off`
      cargo 1.85.1 (d73d2caf9 2024-12-31)
      Rust not found, installing into a temporary directory

      [stderr]
      Python reports SOABI: cpython-312-x86_64-linux-gnu
      Computed rustc target triple: x86_64-unknown-linux-gnu
      Installation directory: /home/jovyan/.cache/puccinialin
      Rustup already downloaded
      Installing rust to /home/jovyan/.cache/puccinialin/rustup
      warn: It looks like you have an existing rustup settings file at:
      warn: /home/jovyan/.rustup/settings.toml
      warn: Rustup will install the default toolchain as specified in the settings file,
      warn: instead of the one inferred from the default host triple.
      info: profile set to 'minimal'
      info: default host triple is x86_64-unknown-linux-gnu
      warn: Updating existing toolchain, profile choice will be ignored
      info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
      info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
      Checking if cargo is installed
      📦 Including license file `LICENSE`
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.12 at /home/jovyan/.cache/uv/builds-v0/.tmpJ5vZA0/bin/python
      📡 Using build options features from pyproject.toml
         Compiling pyo3-build-config v0.22.6
         Compiling opencv v0.93.7
         Compiling pyo3-macros-backend v0.22.6
         Compiling pyo3-ffi v0.22.6
         Compiling pyo3 v0.22.6
         Compiling pyo3-macros v0.22.6
         Compiling numpy v0.22.1
         Compiling trainingsample v0.2.4 (/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src)
      error[E0432]: unresolved import `opencv::core::AlgorithmHint`
       --> src/opencv_ops.rs:6:12
        |
      6 |     core::{AlgorithmHint, Mat},
        |            ^^^^^^^^^^^^^
        |            |
        |            no `AlgorithmHint` in `opencv::hub::core`
        |            help: a similar name exists in the module: `AlgorithmTrait`

      error[E0432]: unresolved import `opencv::core::AlgorithmHint`
       --> src/true_batch_ops.rs:7:12
        |
      7 |     core::{AlgorithmHint, Mat},
        |            ^^^^^^^^^^^^^
        |            |
        |            no `AlgorithmHint` in `opencv::hub::core`
        |            help: a similar name exists in the module: `AlgorithmTrait`

      error[E0061]: this function takes 4 arguments but 5 arguments were supplied
          --> src/opencv_ops.rs:172:9
           |
      172  |         cvt_color(
           |         ^^^^^^^^^
      ...
      177  |             AlgorithmHint::ALGO_HINT_ACCURATE,
           |             --------------------------------- unexpected argument #5
           |
      note: function defined here
          -->
      /home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/target/release/build/opencv-fc91c3ef08d69754/out/opencv/imgproc.rs:5889:9
           |
      5889 |     pub fn cvt_color(src: &impl ToInputArray, dst: &mut impl ToOutputArray, code: i32, dst_cn: i32) -> Result<()> {
           |            ^^^^^^^^^
      help: remove the extra argument
           |
      176  -             0,
      177  -             AlgorithmHint::ALGO_HINT_ACCURATE,
      176  +             0,
           |

      error[E0061]: this function takes 4 arguments but 5 arguments were supplied
          --> src/true_batch_ops.rs:276:13
           |
      276  |             cvt_color(
           |             ^^^^^^^^^
      ...
      281  |                 AlgorithmHint::ALGO_HINT_ACCURATE,
           |                 --------------------------------- unexpected argument #5
           |
      note: function defined here
          -->
      /home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/target/release/build/opencv-fc91c3ef08d69754/out/opencv/imgproc.rs:5889:9
           |
      5889 |     pub fn cvt_color(src: &impl ToInputArray, dst: &mut impl ToOutputArray, code: i32, dst_cn: i32) -> Result<()> {
           |            ^^^^^^^^^
      help: remove the extra argument
           |
      280  -                 0,
      281  -                 AlgorithmHint::ALGO_HINT_ACCURATE,
      280  +                 0,
           |

      Some errors have detailed explanations: E0061, E0432.
      For more information about an error, try `rustc --explain E0061`.
      error: could not compile `trainingsample` (lib) due to 4 previous errors
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_BUILD_EXTENSION_MODULE="1"
      PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/home/jovyan/.cache/uv/builds-v0/.tmpJ5vZA0/bin/python"
      PYTHON_SYS_EXECUTABLE="/home/jovyan/.cache/uv/builds-v0/.tmpJ5vZA0/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module"
      "--features" "python-bindings" "--features" "opencv" "--features" "simd" "--message-format" "json-render-diagnostics" "--manifest-path"
      "/home/jovyan/.cache/uv/sdists-v9/pypi/trainingsample/0.2.4/vrQ6Nip9nLEa84q_ZOhgJ/src/Cargo.toml" "--release" "--lib" "--crate-type" "cdylib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/jovyan/.cache/uv/builds-v0/.tmpJ5vZA0/bin/python', '--compatibility', 'off']
      returned non-zero exit status 1

      hint: This usually indicates a problem with the package or the build environment.
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and syncing.
```

**Comment by bghira** [comment]
you'll need opencv 4.12, looks like you're running 4.10 or earlier

**Comment by bghira** [comment]
```
(.venv) root@C.26398425:~$ pip install trainingsample==0.2.6
Collecting trainingsample==0.2.6
  Downloading trainingsample-0.2.6-cp312-cp312-manylinux_2_39_x86_64.whl.metadata (705 bytes)
Collecting numpy>=1.21.0 (from trainingsample==0.2.6)
  Using cached numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting pillow>=8.0.0 (from trainingsample==0.2.6)
  Using cached pillow-11.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Downloading trainingsample-0.2.6-cp312-cp312-manylinux_2_39_x86_64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 1.5 MB/s eta 0:00:00
Using cached numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached pillow-11.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
Installing collected packages: pillow, numpy, trainingsample
Successfully installed numpy-2.3.3 pillow-11.3.0 trainingsample-0.2.6
```

resolved with trainingsample 0.2.6 for cp311 and cp312 on glibc 2.39

**Comment by janzd** [comment]
I managed to install it after compiling opencv from source and also installing rust.

**Comment by bghira** [comment]
congratulations, that isn't easy. also, the pip wheels work for the future, so you don't need to go through all of that.

**Comment by ZiyiTsang** [comment]
> congratulations, that isn't easy. also, the pip wheels work for the future, so you don't need to go through all of that.

I tried to install pre-compied whell, still fail...
Can you have share **manylinux_2_31** (Used by ubuntu 2004) version?

**Comment by ZiyiTsang** [comment]
Because Ubuntu 2004 has a large user base, I believe it is important to maintain compatibility

**Comment by bghira** [comment]
it's end of life, unfortunately. https://ubuntu.com/blog/ubuntu-20-04-lts-end-of-life-standard-support-is-coming-to-an-end-heres-how-to-prepare

**Comment by ZiyiTsang** [comment]
I successfully installed by compiling OpenCV from source. thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!! this issue is really useful to me.
